"""Utility helpers for TikTok Account Downloader package."""

import os
import re
import tempfile
from typing import Any, Dict, List, Optional, Sequence
from urllib.parse import urlsplit, urlunsplit, urlencode, parse_qsl


def clean_tiktok_url(raw_url: Optional[str]) -> str:
    """Normalize and sanitise an input string into a clean TikTok URL.

    * strips surrounding quotes, backticks and punctuation
    * returns empty string if the input is falsy
    """
    if not raw_url:
        return ""
    url = str(raw_url).strip()
    url = url.strip("`\"'")
    url = url.rstrip(" .,:;")
    url = url.strip("`\"'")
    return url


def is_probably_tiktok_video_url(url: Optional[str]) -> bool:
    """Heuristically detect a TikTok video URL.

    This does not perform a network request; it only inspects the parsed
    URL and checks that the domain is `tiktok.com` and the path matches
    the expected pattern.
    """
    if not url:
        return False
    try:
        parts = urlsplit(url)
    except Exception:
        return False
    host = (parts.netloc or "").lower()
    if host.startswith("www."):
        host = host[4:]
    if host != "tiktok.com":
        return False
    path = parts.path or ""
    return bool(re.search(r"^/@[a-zA-Z0-9_.-]+/video/\d+/?$", path))


def extract_tiktok_video_id(url: Optional[str]) -> Optional[str]:
    """Extract a TikTok numeric video ID from a URL if present.

    Accepts canonical forms with or without a trailing slash.
    """
    cleaned = clean_tiktok_url(url)
    if not cleaned:
        return None
    try:
        path = (urlsplit(cleaned).path or "").strip()
    except Exception:
        return None

    # Match /@user/video/<digits> and optionally a trailing slash.
    match = re.search(r"/@[a-zA-Z0-9_.-]+/video/(\d+)(?:/)?$", path)
    if match:
        return match.group(1)
    return None


def with_tiktok_query_params(url: str, extra_params: Dict[str, Any]) -> str:
    """Return a new URL with the provided query parameters merged in.

    Existing parameters are preserved unless explicitly overridden.
    """
    parts = urlsplit(url)
    existing = dict(parse_qsl(parts.query, keep_blank_values=True))
    existing.update({k: str(v) for k, v in extra_params.items()})
    query = urlencode(existing)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, query, parts.fragment))


def parse_netscape_cookies(file_path: str) -> List[Dict[str, Any]]:
    """Parse a Netscape-format cookies.txt file and return a list of cookie dicts.

    Only TikTok-related domains are retained to reduce noise when loading
    them in Playwright or yt-dlp.
    """
    cookies: List[Dict[str, Any]] = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("#") or not line.strip():
                    continue

                parts = line.strip().split("\t")
                if len(parts) >= 7:
                    domain = parts[0]
                    # Filter domains to tiktok/byteoversea only
                    if "tiktok" not in domain.lower() and "byteoversea" not in domain.lower():
                        continue

                    cookie = {
                        "domain": domain,
                        "path": parts[2],
                        "secure": parts[3].upper() == "TRUE",
                        "expires": float(parts[4]) if parts[4] else -1,
                        "name": parts[5],
                        "value": parts[6],
                    }
                    cookies.append(cookie)
    except Exception:
        # silence any errors; caller can handle empty list
        return []
    return cookies


def write_netscape_cookie_file(cookies: List[Dict[str, Any]]) -> Optional[str]:
    """Dump a list of cookie dictionaries to a temporary Netscape-format file.

    Returns the path to the temporary file, or ``None`` if the input list is
    empty.
    """
    if not cookies:
        return None

    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        delete=False,
        suffix=".cookies.txt",
    )
    try:
        handle.write("# Netscape HTTP Cookie File\n")
        handle.write("# Generated by TikTok Account Downloader\n")
        for c in cookies:
            domain = str(c.get("domain") or "").strip()
            if not domain:
                continue
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = str(c.get("path") or "/")
            secure = "TRUE" if c.get("secure") else "FALSE"
            expires = c.get("expires")
            try:
                expires_f = float(expires) if expires is not None else 0.0
                expires_int = str(int(expires_f)) if expires_f > 0 else "0"
            except Exception:
                expires_int = "0"
            name = str(c.get("name") or "")
            value = str(c.get("value") or "")
            handle.write(
                f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires_int}\t{name}\t{value}\n"
            )
        return handle.name
    finally:
        handle.close()


def file_exists_for_video(output_folder: str, video_id: str) -> bool:
    """Return True if a final media file containing ``video_id`` exists.

    This ignores temporary download artifacts such as ``.part`` or ``.ytdl``
    files by only checking for known completed extensions.
    """
    if not output_folder or not os.path.exists(output_folder):
        return False

    extensions = [".mp4", ".mkv", ".webm", ".ts", ".jpg", ".png"]
    for filename in os.listdir(output_folder):
        if video_id in filename:
            if any(filename.lower().endswith(ext) for ext in extensions):
                return True
    return False


def file_exists_for_video_any(output_folders: Sequence[str], video_id: str) -> bool:
    """Return True if ``video_id`` exists as a completed media file in any folder."""
    for folder in output_folders:
        if file_exists_for_video(folder, video_id):
            return True
    return False
